version: '3.2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes: 
      - ./nginx/log:/var/log/nginx
    ports:
     - "80:80"
    networks:
      - efk
  
  elastic_search:
    container_name: elasticsearch
    restart: always
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - ELASTIC_PASSWORD=changeme%
    networks:
      - efk
      
  kibana:
    container_name: kibana
    restart: always
    build: ./kibana
    ports:
      - "5601:5601"
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    networks:
      - efk
    depends_on:
      - elastic_search


  filebeat:
    container_name: filebeat
    restart: always
    build: ./filebeat
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: ./nginx/log
        target: /var/log/nginx
    networks:
      - efk
    depends_on:
      - nginx
      - elastic_search
      - kibana
    entrypoint: "filebeat -e -strict.perms=false"

networks:
  efk:
    driver: bridge

volumes:
  elasticsearch:
  filebeat: